name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build con Maven
        run: mvn clean install

      - name: Esegui Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Esegui PMD
        run: mvn pmd:check

      - name: Build Docker image
        run: docker build -t dama-app .
